workflows:
  flutter-demo-build:
    name: Flutter Chat Demo Build
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
